mlflow:
  run_name: clear-camelyon-0
  experiment_name: clear-camelyon
data:
  batch_size: 64
  data_root: /hpc/group/engelhardlab/ms1008/image_data
  img_size: 96
  name: camelyon
out_dir: ./out/camelyon
train:
  early_stopping_patience: 5
  epochs: 31
trainer_param:
  beta: 0.1
  channel_split:
  - 4
  - 8
  contrastive_module:
    contrastive_method: SNN
    learnable_temp: true
    pool: gap
    temperature:
    - 0.05
    - 1
    use_dense: false
    use_proj: true
  gamma_c: 1000
  gamma_s: 1000
  vae_lr: 0.0003
vae:
  channel_multipliers:
  - 1
  - 2
  - 4
  - 4
  channels: 32
  n_heads: 4
  n_resnet_blocks: 2
  norm_channels: 32
  x_channels: 3
  z_channels: 12
