mlflow:
  run_name: clear-camelyon-0
  experiment_name: clear-camelyon
data:
  batch_size: 64
  img_size: 96
  n_class: 2
  name: camelyon
out_dir: ./out/camelyon
train:
  early_stopping_patience: 5
  epochs: 31
trainer_param:
  cls_lr: 0.0003
  channel_split:
  - 4
  - 8
vae:
  run_id: null
  model_name: null
cls_model:
  hidden_dim: 256
  out_dim: 2
